----
--- @alias SocketName "spine_01"|"spine_02"|"spine_03"|"spine_04"|"spine_05"|"neck_01"|"neck_02"|"head"|"clavicle_l"|"shoulder_l"|"upperarm_l"|"lowerarm_l"|"hand_l"|"weapon_l"|"clavicle_r"|"shoulder_r"|"upperarm_r"|"lowerarm_r"|"hand_r"|"weapon_r"|"thigh_l"|"calf_l"|"foot_l"|"thigh_r"|"calf_r"|"foot_r"
----
